### ISSUE TITLE
2 Segment Annual Trends Tab

### ISSUE THREAD

**Issue by esherwoo77** [tbep-tech/wq-dash#7]
@fawda123 : Is not rendering the option to select different bay segments (sub-tabs) under both Chrome and Firefox.

**Comment by fawda123** [comment]
@esherwoo77 I can't see this on my end, both in chrome or firefox.  Want to do a quick screenshare?

**Comment by esherwoo77** [comment]
Ok, I think it's a browser scaling issue. When my browser tab is fully maximized the additional bay segment tabs are rendered and accessible. But, when working in a minimized window, the additional bay segment tabs aren't rendered or able to be accessed (attached screenshot). So not so much a bug, but a rendering quirk to work-around. Not a big deal, as long as the info can be accessed in some way.
![image](https://user-images.githubusercontent.com/24903140/105366666-9881d180-5bcd-11eb-930b-5d6be66443df.png)

**Comment by esherwoo77** [comment]
I see what's happening: When the window is minimized to a point where the header text overflows the top banner, then the green header background obscures the top portion of the page body where the additional bay segment tabs are positioned.

**Comment by fawda123** [comment]
Yes, I have had others comment on that.  A simple browser rescale fixes it, but it's not obvious that this needs to be done.  Perhaps a clear statement in the documentation could clear this up or an actual fix to the header scaling behavior somehow...

**Comment by fawda123** [comment]
@esherwoo77 how about this?  I couldn't find a simple fix, but this might be a good workaround. 

https://shiny.tbep.org/wq-dash/

![image](https://user-images.githubusercontent.com/3086881/105770204-e596d800-5f2c-11eb-8f70-c16e841afe94.png)

**Comment by esherwoo77** [comment]
@fawda123 Yes, that header menu fix seems to be working correctly for both a minimized and maximized window and not obscuring the sub-tabs. Thanks for working on a solution. All these dashboards are looking great, and I appreciate your continued refinements and polish on them!
Thanks again.
