### ISSUE TITLE
Sync Site Trends with EPCHC Currents

### ISSUE THREAD

**Issue by emseabee** [tbep-tech/wq-dash#9]
Sync up site trend plots with current year data from EPCHC and hard-code the attainment/annual/seasonal trend plots to show annual to the previous year.

**Comment by fawda123** [comment]
Done here 4292a4d0e907f9294a2f1d63e557666a4153ee36 and here 73e74cc4c8c33d0c7883e69e8c300663ebee94a5.  The site selection data on the map will always be synced with EPC data (within 24 hours), the rest of the plots are fixed to the last year with complete data.
